<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Configurations extends Migration
{
    public function up()
    {
        // Load custom helper
        helper('data_helper');

        $this->forge->addField([
            'config_id' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => false,
                'unique' => true,
            ],
            'config_for' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'unique' => true,
            ],
            'description' => [
                'type' => 'VARCHAR',
                'constraint' => '250',
                'null' => true,
                'default' => null,
            ],
            'config_value' => [
                'type' => 'TEXT',
                'null' => false,
            ],
            'icon' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'null' => true,
                'default' => null,
            ],
            'group' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'data_type' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => false,
                'default' => "Text",
            ],
            'options' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'default_value' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'search_terms' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'deletable' => [
                'type' => 'INT',
                'default' => 1,
            ],
            'created_by' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
            ],
            'updated_by' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);

        $this->forge->addKey('config_id', true);
        $this->forge->createTable('configurations');

        //Insert default record
        $data = [
            [
                'config_id' => getGUID(),
                'config_for' => 'AppApiKey',
                'config_value' => 'your-app-api-key',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-fill',
                'search_terms' => 'api,integration,middleware'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyName',
                'config_value' => 'Igniter CMS App',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-building-line',
                'search_terms' => 'company,name,business,organization'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyEmail',
                'config_value' => 'igniter@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-mail-line',
                'search_terms' => 'email,contact,communication'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanySecondaryEmail',
                'config_value' => 'igniter.support@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-mail-line',
                'search_terms' => 'email,contact,support,communication'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyEnquiryEmail',
                'config_value' => 'contact.us@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-customer-service-line',
                'search_terms' => 'email,enquiry,contact,support'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyNumber',
                'config_value' => '+44 7911 123456',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-phone-line',
                'search_terms' => 'phone,contact,number,telephone'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanySecondaryNumber',
                'config_value' => '+44 7911 654321',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-phone-line',
                'search_terms' => 'phone,contact,number,telephone,secondary'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyAddress',
                'config_value' => '123 Maple Street<br/> Watford, Hertfordshire<br/> WD17 1AA<br/> United Kingdom',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-map-pin-line',
                'search_terms' => 'address,location,office'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyAddressMap',
                'config_value' => '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus" frameborder="0" style="border:0; width: 100%; height: 270px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                'group' => 'site',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-map-2-line',
                'search_terms' => 'map,location,directions,address'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyOpeningHours',
                'config_value' => 'Mon-Fri: 09AM - 05PM',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-time-line',
                'search_terms' => 'address,location,office'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceMode',
                'config_value' => 'No',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceModeTitle',
                'config_value' => 'We\'ll Be Back Soon!',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceModeText',
                'config_value' => 'Our website is currently undergoing scheduled maintenance. <br> Thank you for your patience. Please check back later.',
                'group' => 'site',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],         
            [
                'config_id' => getGUID(),
                'config_for' => 'EmailConfigType',
                'config_value' => 'Mailjet',
                'group' => 'email',
                'data_type' => 'Select',
                'options' => 'SMTP,Mailjet,Mailgun,SendGrid,Postmark',
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-mail-settings-line',
                'search_terms' => 'email,configuration,smtp,mailjet,mailgun,sendgrid,postmark'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SMTPHost',
                'config_value' => 'smtp.mail.com',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-server-line',
                'search_terms' => 'smtp,host,server,email'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SMTPPort',
                'config_value' => '465',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-router-line',
                'search_terms' => 'smtp,port,connection,email'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SMTPUsername',
                'config_value' => 'SmtpUsername',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-user-line',
                'search_terms' => 'smtp,username,credentials,email'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SMTPPassword',
                'config_value' => 'SmtpPassword',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-lock-line',
                'search_terms' => 'smtp,password,credentials,email'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SMTPEncryption',
                'config_value' => 'SSL',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-lock-password-line',
                'search_terms' => 'smtp,encryption,ssl,tls,security'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailgunApiKey',
                'config_value' => 'api-key',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-line',
                'search_terms' => 'mailgun,api,key,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailgunDomain',
                'config_value' => 'domain',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-global-line',
                'search_terms' => 'mailgun,domain,email,configuration'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailgunSenderDomain',
                'config_value' => 'sender-domain',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-mail-send-line',
                'search_terms' => 'mailgun,sender,domain,email'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailgunRegion',
                'config_value' => 'EU',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-earth-line',
                'search_terms' => 'mailgun,region,location,configuration'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SendGridApiKey',
                'config_value' => 'api-key',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-line',
                'search_terms' => 'sendgrid,api,key,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SendGridSenderEmail',
                'config_value' => 'sender-email',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-mail-send-line',
                'search_terms' => 'sendgrid,sender,email,configuration'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SendGridSenderName',
                'config_value' => 'sender-name',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-user-line',
                'search_terms' => 'sendgrid,sender,name,configuration'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PostmarkApiToken',
                'config_value' => 'api-token',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-line',
                'search_terms' => 'postmark,api,token,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PostmarkSenderSignature',
                'config_value' => 'sender-signature',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-file-list-line',
                'search_terms' => 'postmark,sender,signature,configuration'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailjetApiKey',
                'config_value' => 'your-mailjet-api-key',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-line',
                'search_terms' => 'mailjet,api,key,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MailjetApiSecret',
                'config_value' => 'your-mailjet-api-secret',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-lock-password-line',
                'search_terms' => 'mailjet,api,secret,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaTitle',
                'config_value' => 'CodeIgniter CMS | Powerful and Flexible Content Management',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-heading',
                'search_terms' => 'meta,title,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaDescription',
                'config_value' => 'A robust and user-friendly CodeIgniter-based CMS to effortlessly manage your website content.',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-text',
                'search_terms' => 'meta,description,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaKeywords',
                'config_value' => 'codeigniter, cms, content management system, php framework, web development',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'meta,keywords,seo,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaAuthor',
                'config_value' => 'Igniter CMS App',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-user-line',
                'search_terms' => 'meta,author,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaOgImage',
                'config_value' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/ci-cms-logo.jpg',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-image-line',
                'search_terms' => 'meta,og,image,social'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaTitle',
                'config_value' => 'Our Blog | Latest News and Insights',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-article-line',
                'search_terms' => 'blog,meta,title,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaDescription',
                'config_value' => 'Stay updated with the latest news, insights, and articles from our experts. Explore a wide range of topics and join the conversation.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-file-text-line',
                'search_terms' => 'blog,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaKeywords',
                'config_value' => 'blog, news, articles, insights, updates, expert opinions',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'blog,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaTitle',
                'config_value' => 'Upcoming Events | Join Us for Exciting Events',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-calendar-event-line',
                'search_terms' => 'events,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaDescription',
                'config_value' => 'Discover our upcoming events and join us for exciting experiences. Stay informed about dates, locations, and how to participate.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-calendar-todo-line',
                'search_terms' => 'events,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaKeywords',
                'config_value' => 'events, upcoming events, join us, experiences, event dates, event locations',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'events,meta,keywords,tags'
            ],
            
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaTitle',
                'config_value' => 'Contact Us | Get in Touch with Our Team',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-contacts-line',
                'search_terms' => 'contact,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaDescription',
                'config_value' => 'Have questions or need assistance? Get in touch with our team through our contact page. We\'re here to help you with any inquiries.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-chat-3-line',
                'search_terms' => 'contact,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaKeywords',
                'config_value' => 'contact us, get in touch, customer support, inquiries, assistance, help',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'contact,meta,keywords,tags'
            ],    
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaTitle',
                'config_value' => 'Our Portfolio | Showcasing Our Projects',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-gallery-line',
                'search_terms' => 'portfolio,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaDescription',
                'config_value' => 'Explore our portfolio and see the projects we\'ve worked on. Discover our expertise and the quality of our work across various industries.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-gallery-upload-line',
                'search_terms' => 'portfolio,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaKeywords',
                'config_value' => 'portfolio, projects, showcase, our work, expertise, quality projects',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'portfolio,meta,keywords,tags'
            ],    
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaTitle',
                'config_value' => 'Search Results | Find What You\'re Looking For',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-search-line',
                'search_terms' => 'search,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaDescription',
                'config_value' => 'Use our search page to find the information you need. Browse through the search results to locate the content you\'re looking for.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-file-search-line',
                'search_terms' => 'search,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaKeywords',
                'config_value' => 'search, search results, find information, browse content, locate content',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'search,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaTitle',
                'config_value' => 'Filtered Search Results | Refine Your Search',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-filter-line',
                'search_terms' => 'search,filter,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaDescription',
                'config_value' => 'Refine your search results using our filter options. Narrow down the results to find exactly what you\'re looking for quickly and easily.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-filter-2-line',
                'search_terms' => 'search,filter,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaKeywords',
                'config_value' => 'search filter, refine search, filtered results, narrow down, find exactly, search options',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-hashtag',
                'search_terms' => 'search,filter,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for'    => 'SiteLogoLink',
                'config_value'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/ci-cms-logo.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable'    => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-image-2-line',
                'search_terms' => 'logo,site,branding,image'
            ],
            [
                'config_id' => getGUID(),
                'config_for'    => 'SiteLogoTwoLink',
                'config_value'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/ci-cms-logo-horizontal.jpg',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable'    => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-image-2-line',
                'search_terms' => 'logo,site,branding,image'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLink',
                'config_value' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/favicon/favicon.ico',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-image-line',
                'search_terms' => 'favicon,site,icon,browser'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLink96',
                'config_value' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/favicon/favicon-96x96.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-image-line',
                'search_terms' => 'favicon,96,site,icon'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLinkAppleTouch',
                'config_value' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/favicon/apple-touch-icon.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-apple-line',
                'search_terms' => 'favicon,apple,touch,icon'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconManifestLink',
                'config_value' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/logo/favicon/site.webmanifest',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-file-list-3-line',
                'search_terms' => 'favicon,manifest,site,web'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FrontEndFormat',
                'config_value' => 'MVC',
                'group' => 'api',
                'data_type' => 'Select',
                'options' => 'MVC,API',
                'default_value' => 'MVC',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-layout-2-line',
                'search_terms' => 'frontend,format,mvc,api'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'RequireApiGet',
                'config_value' => 'Yes',
                'group' => 'api',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-download-cloud-line',
                'search_terms' => 'api,get,require,access'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'RequireApiPost',
                'config_value' => 'Yes',
                'group' => 'api',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-upload-cloud-line',
                'search_terms' => 'api,post,require,access'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'AllowedApiGetModels',
                'config_value' => 'Blogs, Categories, Codes, Configurations, Contacts, ContactMessages, ContentBlocks, Counters, Countries, Events, Faqs, FileUploads, HomePage, Languages, Navigations, Pages, Partners, Policies, Portfolios, Pricings, Services, Socials, Teams, Testimonials, Themes, Translations, Users',
                'group' => 'api',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-database-2-line',
                'search_terms' => 'api,get,models,allowed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'AllowedApiPostModels',
                'config_value' => 'Blogs, Categories, Codes, Configurations, Contacts, ContactMessages, ContentBlocks, Counters, Countries, Events, Faqs, FileUploads, HomePage, Languages, Navigations, Pages, Partners, Policies, Portfolios, Pricings, Services, Socials, Teams, Testimonials, Themes, Translations, Users',
                'group' => 'api',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-database-2-line',
                'search_terms' => 'api,post,models,allowed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseCaptcha',
                'config_value' => 'No',
                'group' => 'forms',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'captcha,security,forms,spam'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HCaptchaSiteKey',
                'config_value' => '',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'hCaptcha is a platform that stops online fraud and abuse with no personal information. It offers high accuracy, low friction, and universal compatibility for web, mobile, and server-side use cases. Learn more: https://www.hcaptcha.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-2-line',
                'search_terms' => 'recaptcha,key,site,hcaptcha'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HCaptchaSecretKey',
                'config_value' => 'ES_XXXXXXXXXX',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'hCaptcha is a platform that stops online fraud and abuse with no personal information. It offers high accuracy, low friction, and universal compatibility for web, mobile, and server-side use cases. Learn more: https://www.hcaptcha.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-key-line',
                'search_terms' => 'recaptcha,secret,key,hcaptcha'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseShareThis',
                'config_value' => 'No',
                'group' => 'share',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'ShareThis official site. Digital data solutions for media planning, targeting, and measurement. Website tools to grow online audiences. Learn more: https://sharethis.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-share-line',
                'search_terms' => 'share,social,buttons,sharing'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ShareThisCode',
                'config_value' => '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6XXXXXXXXXXXXXXXXXX&product=sticky-share-buttons&source=platform" async="async"></script>',
                'group' => 'share',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'You can install the ShareThis share button on your HTML website in a few easy steps. Navigate to the setup page and choose your preference of Inline Buttons or Sticky Buttons. Learn more: https://sharethis.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-share-line',
                'search_terms' => 'share,code,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseGoogleAnalytics',
                'config_value' => 'No',
                'group' => 'analytics',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-bar-chart-line',
                'search_terms' => 'analytics,google,tracking'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'GoogleTagManagerHead',
                'config_value' => "<!--Google Tag Manager--><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-XXXXXX');</script><!--End Google Tag Manager-->",
                'group' => 'analytics',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-google-line',
                'search_terms' => 'analytics,google,tag manager'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'GoogleTagManagerBody',
                'config_value' => '<!--Google Tag Manager (noscript)--><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!--End Google Tag Manager (noscript)-->',
                'group' => 'analytics',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-google-line',
                'search_terms' => 'analytics,google,tag manager'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseFacebookPixel',
                'config_value' => 'No',
                'group' => 'analytics',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-facebook-circle-line',
                'search_terms' => 'analytics,facebook,pixel'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FacebookPixelCode',
                'config_value' => '<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window, document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');fbq(\'init\', \'YOUR_PIXEL_ID\');fbq(\'track\', \'PageView\');</script><noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=YOUR_PIXEL_ID&ev=PageView&noscript=1" /></noscript>',
                'group' => 'analytics',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-facebook-circle-line',
                'search_terms' => 'analytics,facebook,pixel'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UsePostHog',
                'config_value' => 'No',
                'group' => 'forms',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'analytics,posthog,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PostHog',
                'config_value' => '<script>!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(t,o,n){    function i(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){    t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}var s=e;for(void 0!==n?s=e[n]=[]:n="posthog",    s.people=s.people||[],s.toString=function(t){var e="posthog";return"posthog"!==n&&(e+="."+n),t||(e+=" (stub)"),e},    s.people.toString=function(){return s.toString(1)+".people (stub)"};p="capture identify alias people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" "),    r=0;r<p.length;r++)i(s,p[r]);e._i.push([t,o,n])},e.__SV=1.0,o=t.createElement("script"),    o.type="text/javascript",o.async=!0,o.src="https://cdn.posthog.com/posthog.js",n=t.getElementsByTagName("script")[0],    n.parentNode.insertBefore(o,n))}(document,window.posthog||[]);    posthog.init("YOUR_PROJECT_API_KEY", {api_host: "https://app.posthog.com"});</script>',
                'group' => 'share',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Add this snippet to your website within the <head> tag and you\'ll be ready to start using PostHog. Learn more: https://posthog.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'analytics,posthog,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableSocialAutoPosting',
                'config_value' => 'No',
                'group' => 'social',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-share-forward-line',
                'search_terms' => 'social,auto posting'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FacebookPageAccessToken',
                'config_value' => 'EAABEXAMPLEEXAMPLETOKEN',
                'group' => 'social',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-facebook-circle-line',
                'search_terms' => 'social,facebook,access token'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseCookieConcent',
                'config_value' => 'No',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Cookie Consent solution for your website to comply with ePrivacy Directive & GDPR. See options: https://termly.io/, https://www.freeprivacypolicy.com/free-cookie-consent/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'security,cookie,consent'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CookieConcentCode',
                'config_value' => '<!-- Cookie Consent by https://www.FreePrivacyPolicy.com --> <script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/3.1.0/cookie-consent.js"></script> <script type="text/javascript"> document.addEventListener(’DOMContentLoaded’, function () { cookieconsent.run({"notice_banner_type":"headline","consent_type":"express","palette":"light","language":"en","website_name":"YOUR WEBSITE NAME"}); }); </script>',
                'group' => 'security',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Cookie Consent solution for your website to comply with ePrivacy Directive & GDPR. See options: https://termly.io/, https://www.freeprivacypolicy.com/free-cookie-consent/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'security,cookie,consent'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseTwitterFeed',
                'config_value' => 'No',
                'group' => 'analytics',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-twitter-line',
                'search_terms' => 'analytics,twitter,feed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'TwitterFeedCode',
                'config_value' => '<a class="twitter-timeline" data-width="400" data-height="500" href="https://twitter.com/your_twitter_handle?ref_src=twsrc%5Etfw">Tweets by your_twitter_handle</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
                'group' => 'security',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-twitter-line',
                'search_terms' => 'analytics,twitter,feed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnablePaymentGateway',
                'config_value' => 'No',
                'group' => 'ecommerce',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-bank-card-line',
                'search_terms' => 'ecommerce,payment,gateway'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'StripeAPIKey',
                'config_value' => 'sk_test_EXAMPLEKEY12345',
                'group' => 'ecommerce',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-bank-card-line',
                'search_terms' => 'ecommerce,payment,stripe'            
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableErrorTracking',
                'config_value' => 'No',
                'group' => 'debugging',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-bug-line',
                'search_terms' => 'debugging,error,tracking'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SentryDSN',
                'config_value' => '',
                'group' => 'debugging',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-bug-line',
                'search_terms' => 'debugging,error,sentry'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'AIHelpChatType',
                'config_value' => 'Gemini',
                'group' => 'ai',
                'data_type' => 'Select',
                'options' => 'Gemini',
                'default_value' => 'Gemini',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-robot-2-fill',
                'search_terms' => 'ai,chat,help,gemini,deepseek,qwen,gpt'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'AIHelpChatKey',
                'config_value' => '',
                'group' => 'ai',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-robot-2-fill',
                'search_terms' => 'ai,api key,chat,help,gemini,deepseek,qwen,gpt'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableChatbot',
                'config_value' => 'Yes',
                'group' => 'chatbot',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'chatbot,enable'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ChatbotCode',
                'config_value' => '<!--Start of Tawk.to Script--><script type="text/javascript">var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();(function(){var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];s1.async=true;s1.src="https://embed.tawk.to/[tawk.to.code]";s1.charset="UTF-8";s1.setAttribute("crossorigin","*");s0.parentNode.insertBefore(s1,s0);})();</script><!--End of Tawk.to Script-->',
                'group' => 'chatbot',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Integrate chatbots and monitor customer activity in real time. See optionslike: https://www.tawk.to/, https://zapier.com/, https://botpress.com/, https://webagent.ai/, https://botpenguin.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'chatbot,tawk.to'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableGoogleTranslate',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => '',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-earth-line',
                'search_terms' => 'translate,google,language'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HoneypotKey',
                'config_value' => 'igniter_hpot_val',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => 'igniter_hpot_val',
                'deletable' => 0,
                'description' => 'This is the input name for your honeypot input.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-shield-keyhole-fill',
                'search_terms' => 'honeypot,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'TimestampKey',
                'config_value' => 'igniter_timestamp_val',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => 'igniter_timestamp_val',
                'deletable' => 0,
                'description' => 'This is the input name for your timestamp bot detector.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-shield-keyhole-fill',
                'search_terms' => 'honeypot,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaxFailedAttempts',
                'config_value' => '5',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => '5',
                'deletable' => 0,
                'description' => 'This is maximum failed login attempts allowed in one session.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-lock-fill',
                'search_terms' => 'failed login,locked out,security'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FailedLoginsSuspensionPeriod',
                'config_value' => '+30 minutes',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => '+5 minutes,+10 minutes,+30 minutes,+1 hour,+3 hours,+24 hours',
                'default_value' => '+30 minutes',
                'deletable' => 0,
                'description' => 'This is suspension period for multiple failed logins.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-time-fill',
                'search_terms' => 'suspension,failed login,locked out,security, timeout'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlockedIPSuspensionPeriod',
                'config_value' => '+3 years',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => '+1 day,+1 days,+1 month,+3 months,+6 months,+1 year,+3 years,+5 years,+10 years',
                'default_value' => '+3 years',
                'deletable' => 0,
                'description' => 'This is suspension period for suspended IP\'s.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-time-fill',
                'search_terms' => 'suspension,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaxUploadFileSize',
                'config_value' => '1',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => '1,3,5,10,50,100,1000',
                'default_value' => '5',
                'deletable' => 0,
                'description' => 'This is the maximum file upload size in megabytes.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'icon' => 'ri-upload-cloud-fill',
                'search_terms' => 'file upload,maximum,file size'
            ],
        ];

        // Using Query Builder
        $this->db->table('configurations')->insertBatch($data);
    }

    public function down()
    {
        $this->forge->dropTable('configurations');
    }
}

