<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Portfolios extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'portfolio_id' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
            ],
            'title' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
            ],
            'description' => [
                'type' => 'TEXT',
                'constraint' => '1000',
                'null' => true,
                'default' => null,
            ],
            'slug' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
            ],
            'category' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'category_filter' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'group' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'null' => true,
                'default' => 'portfolio',
            ],
            'client' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'project_date' => [
                'type' => 'DATE',
                'null' => true,
            ],
            'project_url' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'featured_image' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'details_image_1' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'details_image_2' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'details_image_3' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'details_image_4' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'content' => [
                'type' => 'TEXT',
            ],
            'status' => [
                'type' => 'INT',
                'default' => 0,
                'null' => true,
            ],
            'total_views' => [
                'type' => 'INT',
                'default' => 0,
                'null' => true,
            ],
            'created_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'updated_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'meta_title' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'meta_description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'meta_keywords' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);
        $this->forge->addKey('portfolio_id', true);

        // Custom Optimization - Indexing
        $this->forge->addKey('title');

        $this->forge->createTable('portfolios');

        //insert default records
        //----------------------
        $data = [
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa1'),
                'title' => 'Website Redesign',
                'description' => 'A complete overhaul of the client\'s existing website to improve user experience and update the design.',
                'slug' => 'website-redesign',
                'category' => 'Web Development',
                'category_filter' => 'web-development',
                'group' => 'portfolio',
                'client' => 'TechCorp',
                'project_date' => '2024-01-15',
                'project_url' => 'https://example.com/?techcorp=new-website',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-1.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-1.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-2.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-3.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-4.jpg',
                'content' => '<p>We worked closely with TechCorp to redesign their website, focusing on a modern look and feel, as well as improving the overall user experience. The project included a new responsive design, updated content structure, and enhanced performance.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Website Redesign for TechCorp',
                'meta_description' => 'Read about our project to redesign TechCorp\'s website, focusing on user experience and modern design.',
                'meta_keywords' => 'website redesign, web development, TechCorp, user experience, responsive design'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa2'),
                'title' => 'Mobile App Development',
                'description' => 'Development of a cross-platform mobile app for a retail client to enhance their customer engagement.',
                'slug' => 'mobile-app-development',
                'category' => 'App Development',
                'category_filter' => 'app-development',
                'group' => 'portfolio',
                'client' => 'RetailGiant',
                'project_date' => '2024-02-20',
                'project_url' => 'https://example.com/?retailgiant=mobile-app',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-2.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-1.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-2.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-3.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-4.jpg',
                'content' => '<p>Our team developed a cross-platform mobile app for RetailGiant, designed to enhance customer engagement and provide a seamless shopping experience. The app includes features such as push notifications, in-app purchases, and loyalty rewards.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Mobile App Development for RetailGiant',
                'meta_description' => 'Discover how we developed a cross-platform mobile app for RetailGiant to enhance customer engagement.',
                'meta_keywords' => 'mobile app development, app development, RetailGiant, customer engagement, cross-platform'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa3'),
                'title' => 'E-commerce Platform Launch',
                'description' => 'Launch of a new e-commerce platform for a fashion brand, including design, development, and deployment.',
                'slug' => 'ecommerce-platform-launch',
                'category' => 'E-commerce',
                'category_filter' => 'e-commerce',
                'group' => 'portfolio',
                'client' => 'FashionHub',
                'project_date' => '2024-03-10',
                'project_url' => 'https://example.com?fashionhub',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-3.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-1.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-2.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-3.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-4.jpg',
                'content' => '<p>We partnered with FashionHub to launch a new e-commerce platform, providing end-to-end services from design and development to deployment. The platform offers a user-friendly interface, secure payment options, and an integrated inventory management system.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'E-commerce Platform Launch for FashionHub',
                'meta_description' => 'Learn about our project to launch a new e-commerce platform for FashionHub, including design, development, and deployment.',
                'meta_keywords' => 'e-commerce platform, e-commerce, FashionHub, platform launch, web development'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa4'),
                'title' => 'Digital Marketing Campaign',
                'description' => 'A comprehensive digital marketing campaign for a new product launch, including SEO, SEM, and social media marketing.',
                'slug' => 'digital-marketing-campaign',
                'category' => 'Marketing',
                'category_filter' => 'marketing',
                'group' => 'portfolio',
                'client' => 'Innovatech',
                'project_date' => '2024-04-05',
                'project_url' => 'https://example.com/?innovatech=new-product',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-4.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-1.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-2.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-3.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-4.jpg',
                'content' => '<p>Innovatech engaged us to run a digital marketing campaign for their new product launch. The campaign included SEO to improve search engine rankings, SEM for targeted advertising, and social media marketing to increase brand awareness and engagement.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Digital Marketing Campaign for Innovatech',
                'meta_description' => 'Explore our digital marketing campaign for Innovatech\'s new product launch, including SEO, SEM, and social media marketing.',
                'meta_keywords' => 'digital marketing, marketing campaign, Innovatech, SEO, SEM, social media marketing'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa5'),
                'title' => 'Truffle Arancini',
                'description' => 'Crispy risotto balls infused with black truffle and melted mozzarella, served with a truffle aioli.',
                'slug' => 'truffle-arancini',
                'category' => 'Starters',
                'category_filter' => 'starters',
                'group' => 'restaurant_portfolio',
                'client' => 'Gourmet Bistro',
                'project_date' => '2024-01-10',
                'project_url' => 'https://example.com/menu/starters',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-5.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our signature truffle arancini combines premium Italian risotto with black truffle essence and gooey mozzarella center, fried to golden perfection. Served with our house-made truffle aioli for dipping.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Truffle Arancini Starter | Gourmet Bistro',
                'meta_description' => 'Experience our crispy truffle-infused risotto balls with melted mozzarella center, served with truffle aioli.',
                'meta_keywords' => 'truffle arancini, Italian starter, gourmet appetizer, truffle dishes'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa6'),
                'title' => 'Pan-Seared Scallops',
                'description' => 'Fresh scallops seared to perfection, served with pea puree and crispy pancetta.',
                'slug' => 'pan-seared-scallops',
                'category' => 'Starters',
                'category_filter' => 'starters',
                'group' => 'restaurant_portfolio',
                'client' => 'Coastal Kitchen',
                'project_date' => '2024-02-15',
                'project_url' => 'https://example.com/menu/starters',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-6.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our pan-seared scallops are cooked to tender perfection with a golden crust, served on a bed of smooth pea puree and topped with crispy pancetta bits. A perfect balance of sweet and savory flavors.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Pan-Seared Scallops Starter | Coastal Kitchen',
                'meta_description' => 'Delicate scallops seared to perfection with pea puree and crispy pancetta - a perfect starter.',
                'meta_keywords' => 'scallops starter, seafood appetizer, pan-seared scallops, gourmet starter'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa7'),
                'title' => 'Filet Mignon',
                'description' => 'Premium cut of beef tenderloin, cooked to perfection and served with truffle mashed potatoes.',
                'slug' => 'filet-mignon',
                'category' => 'Main Courses',
                'category_filter' => 'main-courses',
                'group' => 'restaurant_portfolio',
                'client' => 'Steakhouse Prime',
                'project_date' => '2024-03-20',
                'project_url' => 'https://example.com/menu/main-courses',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-7.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our 8oz filet mignon is cut from premium beef tenderloin, aged for tenderness and flavor. Cooked to your preferred temperature and served with creamy truffle mashed potatoes and seasonal vegetables. The perfect centerpiece for any special occasion.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Filet Mignon Main Course | Steakhouse Prime',
                'meta_description' => 'Premium beef tenderloin cooked to perfection with truffle mashed potatoes - a steak lover\'s dream.',
                'meta_keywords' => 'filet mignon, steak, beef tenderloin, main course, gourmet steak'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa8'),
                'title' => 'Lobster Risotto',
                'description' => 'Creamy Arborio rice cooked with lobster stock and topped with fresh lobster meat.',
                'slug' => 'lobster-risotto',
                'category' => 'Main Courses',
                'category_filter' => 'main-courses',
                'group' => 'restaurant_portfolio',
                'client' => 'Seafood Haven',
                'project_date' => '2024-04-05',
                'project_url' => 'https://example.com/menu/main-courses',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-8.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our lobster risotto features creamy Arborio rice slowly cooked in rich lobster stock, finished with butter and parmesan. Topped with generous portions of fresh, succulent lobster meat and garnished with chives. A luxurious seafood experience.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Lobster Risotto Main Course | Seafood Haven',
                'meta_description' => 'Creamy risotto cooked in lobster stock and topped with fresh lobster meat - a seafood lover\'s delight.',
                'meta_keywords' => 'lobster risotto, seafood main course, gourmet risotto, Italian cuisine'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66afa9'),
                'title' => 'Chocolate Soufflé',
                'description' => 'Light and airy chocolate soufflé with a molten center, served with vanilla bean ice cream.',
                'slug' => 'chocolate-souffle',
                'category' => 'Desserts',
                'category_filter' => 'desserts',
                'group' => 'restaurant_portfolio',
                'client' => 'Sweet Indulgence',
                'project_date' => '2024-01-25',
                'project_url' => 'https://example.com/menu/desserts',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-9.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our signature chocolate soufflé is a masterpiece of dessert engineering - light and airy on the outside with a decadent molten chocolate center. Baked to order and served warm with a scoop of house-made vanilla bean ice cream for the perfect temperature contrast.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Chocolate Soufflé Dessert | Sweet Indulgence',
                'meta_description' => 'Light chocolate soufflé with molten center, served with vanilla bean ice cream - the perfect dessert.',
                'meta_keywords' => 'chocolate soufflé, gourmet dessert, chocolate dessert, French pastry'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66af10'),
                'title' => 'Berry Pavlova',
                'description' => 'Crisp meringue shell filled with whipped cream and fresh seasonal berries.',
                'slug' => 'berry-pavlova',
                'category' => 'Desserts',
                'category_filter' => 'desserts',
                'group' => 'restaurant_portfolio',
                'client' => 'Garden Café',
                'project_date' => '2024-02-28',
                'project_url' => 'https://example.com/menu/desserts',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-10.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our berry pavlova features a crisp yet chewy meringue shell filled with lightly sweetened whipped cream and topped with an assortment of fresh seasonal berries. The perfect balance of textures and flavors - sweet meringue, creamy filling, and tart berries.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Berry Pavlova Dessert | Garden Café',
                'meta_description' => 'Crisp meringue with whipped cream and fresh berries - a light and refreshing dessert option.',
                'meta_keywords' => 'pavlova, berry dessert, meringue dessert, summer dessert'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66af11'),
                'title' => 'Signature Cocktails',
                'description' => 'Our award-winning mixologists create innovative cocktails using premium spirits and fresh ingredients.',
                'slug' => 'signature-cocktails',
                'category' => 'Drinks',
                'category_filter' => 'drinks',
                'group' => 'restaurant_portfolio',
                'client' => 'Mixology Bar',
                'project_date' => '2024-03-15',
                'project_url' => 'https://example.com/menu/drinks',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-11.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our signature cocktails are crafted by award-winning mixologists using premium spirits, house-made syrups, and fresh ingredients. From classic cocktails with a twist to completely original creations, each drink is a work of art designed to complement your dining experience.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Signature Cocktails | Mixology Bar',
                'meta_description' => 'Award-winning cocktails crafted by our mixologists using premium spirits and fresh ingredients.',
                'meta_keywords' => 'signature cocktails, mixology, craft cocktails, premium drinks'
            ],
            [
                'portfolio_id' => getGUID('3fa85f64-5717-4562-b3fc-2c963f66af12'),
                'title' => 'Coffee Selection',
                'description' => 'Curated selection of international coffee, carefully chosen to complement our menu.',
                'slug' => 'coffee-selection',
                'category' => 'Drinks',
                'category_filter' => 'drinks',
                'group' => 'restaurant_portfolio',
                'client' => 'Vineyard Cellar',
                'project_date' => '2024-04-10',
                'project_url' => 'https://example.com/menu/drinks',
                'featured_image' => 'public/uploads/files/portfolio/portfolio-image-12.jpg',
                'details_image_1' => 'public/uploads/files/portfolio/gallery-5.jpg',
                'details_image_2' => 'public/uploads/files/portfolio/gallery-6.jpg',
                'details_image_3' => 'public/uploads/files/portfolio/gallery-7.jpg',
                'details_image_4' => 'public/uploads/files/portfolio/gallery-8.jpg',
                'content' => '<p>Our carefully curated coffee selection features bottles from renowned vineyards around the world. Our sommelier has chosen each coffee to complement specific dishes on our menu, with options ranging from crisp whites to full-bodied reds and everything in between. Ask about our coffee pairing suggestions for the perfect dining experience.</p>',
                'status' => 1,
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'meta_title' => 'Wine Selection | Vineyard Cellar',
                'meta_description' => 'Curated selection of international coffees chosen to perfectly complement our menu offerings.',
                'meta_keywords' => 'coffee selection, coffee pairing, roasted coffees'
            ]
        ];

        // Using Query Builder
        $this->db->table('portfolios')->insertBatch($data);

    }

    public function down()
    {
        $this->forge->dropTable('portfolios');
    }
}
