<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class Configurations extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'config_id' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => false,
                'unique' => true,
            ],
            'config_for' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'unique' => true,
            ],
            'description' => [
                'type' => 'TEXT',
                'constraint' => '1000',
                'null' => true,
                'default' => null,
            ],
            'config_value' => [
                'type' => 'TEXT',
                'null' => false,
            ],
            'icon' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'null' => true,
                'default' => null,
            ],
            'group' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'null' => true,
                'default' => null,
            ],
            'data_type' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => false,
                'default' => "Text",
            ],
            'options' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'default_value' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'custom_class' => [
                'type' => 'VARCHAR',
                'constraint' => '100',
                'null' => true,
                'default' => null,
            ],
            'search_terms' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
                'default' => null,
            ],
            'deletable' => [
                'type' => 'INT',
                'default' => 1,
            ],
            'created_by' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
            ],
            'updated_by' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);

        $this->forge->addKey('config_id', true);

        $this->forge->createTable('configurations');

        //Insert default record
        $data = [
            [
                'config_id' => getGUID(),
                'config_for' => 'HomePageFormat',
                'config_value' => 'HomePage',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'HomePage,Blog,Shop,Portfolio,None',
                'default_value' => 'HomePage',
                'deletable' => 0,
                'description' => 'Enable or disable maintenance mode for the site.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-pages-fill',
                'search_terms' => 'Home page,blogs,resumes,shops,portfolioslayout,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyName',
                'config_value' => 'Igniter CMS App',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Name of the company or organization.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'title-text',
                'icon' => 'ri-building-line',
                'search_terms' => 'company,name,business,organization'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyEmail',
                'config_value' => 'igniter@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Primary contact email for the company.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'email',
                'icon' => 'ri-mail-line',
                'search_terms' => 'email,contact,communication'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanySecondaryEmail',
                'config_value' => 'igniter.support@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Secondary contact email for support or general inquiries.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'email',
                'icon' => 'ri-mail-line',
                'search_terms' => 'email,contact,support,communication'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyEnquiryEmail',
                'config_value' => 'contact.us@mail.com',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Email address for receiving general enquiries or contact form submissions.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'email',
                'icon' => 'ri-customer-service-line',
                'search_terms' => 'email,enquiry,contact,support'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyNumber',
                'config_value' => '+44 7911 123456',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Primary contact phone number for the company.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'phone-number',
                'icon' => 'ri-phone-line',
                'search_terms' => 'phone,contact,number,telephone'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanySecondaryNumber',
                'config_value' => '+44 7911 654321',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Secondary contact phone number for the company.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'phone-number',
                'icon' => 'ri-phone-line',
                'search_terms' => 'phone,contact,number,telephone,secondary'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyAddress',
                'config_value' => '123 Maple Street<br/> Watford, Hertfordshire<br/> WD17 1AA<br/> United Kingdom',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Physical address of the company office.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'title-text',
                'icon' => 'ri-map-pin-line',
                'search_terms' => 'address,location,office'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyAddressMap',
                'config_value' => '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus" frameborder="0" style="border:0; width: 100%; height: 270px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                'group' => 'site',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Embedded map code to display the company location.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-map-2-line',
                'search_terms' => 'map,location,directions,address'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CompanyOpeningHours',
                'config_value' => 'Mon-Fri: 09AM - 05PM',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Operating hours of the company.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-time-line',
                'search_terms' => 'address,location,office'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceMode',
                'config_value' => 'No',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable maintenance mode for the site.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceModeTitle',
                'config_value' => 'We\'ll Be Back Soon!',
                'group' => 'site',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Title displayed during maintenance mode.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'title-text',
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaintenanceModeText',
                'config_value' => 'Our website is currently undergoing scheduled maintenance. <br> Thank you for your patience. Please check back later.',
                'group' => 'site',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Message displayed during maintenance mode.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-settings-line',
                'search_terms' => 'maintenance,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableRegistration',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable user registration/signup functionality.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-settings-line',
                'search_terms' => 'registration,sign up,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnablePortfoliosPage',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the projects/portfolio page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-gallery-view-2',
                'search_terms' => 'portfolios,project,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableShopFront',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the store front.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shopping-cart-fill',
                'search_terms' => 'ecommerce,shop,products,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableEventsPage',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the events page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-calendar-event-line',
                'search_terms' => 'events,calendar,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableDonationsPage',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the donations and causes page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-money-pound-circle-fill',
                'search_terms' => 'charity,donations,crowdfunding,mode,status,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableAppointmentsPage',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the appointments page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-calendar-schedule-line',
                'search_terms' => 'calendar,appointments,booking,scheduling,meetings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnablePopupAds',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'This configuration enables or disables the popup ads for the home page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-advertisement-line',
                'search_terms' => 'popup,advert,alerts,announcements,pop-up'
            ], 
            [
                'config_id' => getGUID(),
                'config_for' => 'ResendAPI',
                'config_value' => 'your-resend-api',
                'group' => 'email',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'API key for Resend email service.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-lock-password-line',
                'search_terms' => 'resend,api,secret,credentials'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaTitle',
                'config_value' => 'CodeIgniter CMS | Powerful and Flexible Content Management',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Main title for SEO and meta tags',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-heading',
                'search_terms' => 'meta,title,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaDescription',
                'config_value' => 'A robust and user-friendly CodeIgniter-based CMS to effortlessly manage your website content.',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Description for SEO and meta tags',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-text',
                'search_terms' => 'meta,description,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaKeywords',
                'config_value' => 'codeigniter, cms, content management system, php framework, web development',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Keywords for SEO and meta tags',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'meta,keywords,seo,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaAuthor',
                'config_value' => 'Igniter CMS App',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Author information for SEO and meta tags',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-user-line',
                'search_terms' => 'meta,author,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MetaOgImage',
                'config_value' => 'public/uploads/files/ci-cms-logo.jpg',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Open Graph image for social media sharing.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-line',
                'search_terms' => 'meta,og,image,social'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaTitle',
                'config_value' => 'Our Blog | Latest News and Insights',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the blogs page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-article-line',
                'search_terms' => 'blog,meta,title,seo,page'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaDescription',
                'config_value' => 'Stay updated with the latest news, insights, and articles from our experts. Explore a wide range of topics and join the conversation.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the blogs page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-file-text-line',
                'search_terms' => 'blog,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlogsPageMetaKeywords',
                'config_value' => 'blog, news, articles, insights, updates, expert opinions',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the blogs page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'blog,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaTitle',
                'config_value' => 'Upcoming Events | Join Us for Exciting Events',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the events page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-calendar-event-line',
                'search_terms' => 'events,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaDescription',
                'config_value' => 'Discover our upcoming events and join us for exciting experiences. Stay informed about dates, locations, and how to participate.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the events page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-calendar-todo-line',
                'search_terms' => 'events,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EventsPageMetaKeywords',
                'config_value' => 'events, upcoming events, join us, experiences, event dates, event locations',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the events page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'events,meta,keywords,tags'
            ],
            
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaTitle',
                'config_value' => 'Contact Us | Get in Touch with Our Team',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the contact us page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-contacts-line',
                'search_terms' => 'contact,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaDescription',
                'config_value' => 'Have questions or need assistance? Get in touch with our team through our contact page. We\'re here to help you with any inquiries.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the contact us page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-chat-3-line',
                'search_terms' => 'contact,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ContactUsPageMetaKeywords',
                'config_value' => 'contact us, get in touch, customer support, inquiries, assistance, help',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the contact us page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'contact,meta,keywords,tags'
            ],    
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaTitle',
                'config_value' => 'Our Portfolio | Showcasing Our Projects',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the portfolios page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-gallery-line',
                'search_terms' => 'portfolio,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaDescription',
                'config_value' => 'Explore our portfolio and see the projects we\'ve worked on. Discover our expertise and the quality of our work across various industries.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the portfolios page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-gallery-upload-line',
                'search_terms' => 'portfolio,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PortfoliosPageMetaKeywords',
                'config_value' => 'portfolio, projects, showcase, our work, expertise, quality projects',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the portfolios page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'portfolio,meta,keywords,tags'
            ],    
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaTitle',
                'config_value' => 'Search Results | Find What You\'re Looking For',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-search-line',
                'search_terms' => 'search,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaDescription',
                'config_value' => 'Use our search page to find the information you need. Browse through the search results to locate the content you\'re looking for.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-file-search-line',
                'search_terms' => 'search,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchPageMetaKeywords',
                'config_value' => 'search, search results, find information, browse content, locate content',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'search,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaTitle',
                'config_value' => 'Filtered Search Results | Refine Your Search',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta title for the filtered search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-filter-line',
                'search_terms' => 'search,filter,meta,title,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaDescription',
                'config_value' => 'Refine your search results using our filter options. Narrow down the results to find exactly what you\'re looking for quickly and easily.',
                'group' => 'meta_seo',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta description for the filtered search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-filter-2-line',
                'search_terms' => 'search,filter,meta,description,seo'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SearchFilterPageMetaKeywords',
                'config_value' => 'search filter, refine search, filtered results, narrow down, find exactly, search options',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Meta keywords for the filtered search results page.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-hashtag',
                'search_terms' => 'search,filter,meta,keywords,tags'
            ],
            [
                'config_id' => getGUID(),
                'config_for'    => 'BackendLogoLink',
                'config_value'    => 'public/uploads/files/ci-cms-logo.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable'    => 0,
                'description' => 'Logo link for the backend interface.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-2-line',
                'search_terms' => 'logo,site,branding,image'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BackendFaviconLink',
                'config_value' => 'public/uploads/files/favicon/favicon.ico',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Favicon link for the backend interface.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-line',
                'search_terms' => 'favicon,site,icon,browser'
            ],
            [
                'config_id' => getGUID(),
                'config_for'    => 'SiteLogoLink',
                'config_value'    => 'public/uploads/files/ci-cms-logo.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable'    => 0,
                'description' => 'Logo link for the frontend interface (PNG format).',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-2-line',
                'search_terms' => 'logo,site,branding,image'
            ],
            [
                'config_id' => getGUID(),
                'config_for'    => 'SiteLogoTwoLink',
                'config_value'    => 'public/uploads/files/ci-cms-logo-horizontal.jpg',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable'    => 0,
                'description' => 'Logo link for the frontend interface (JPG format).',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-2-line',
                'search_terms' => 'logo,site,branding,image'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLink',
                'config_value' => 'public/uploads/files/favicon/favicon.ico',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Favicon link for the frontend interface.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-line',
                'search_terms' => 'favicon,site,icon,browser'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLink96',
                'config_value' => 'public/uploads/files/favicon/favicon-96x96.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Favicon link for the frontend interface (96x96 size).',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-image-line',
                'search_terms' => 'favicon,96,site,icon'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconLinkAppleTouch',
                'config_value' => 'public/uploads/files/favicon/apple-touch-icon.png',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Apple touch icon link for the frontend interface.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-apple-line',
                'search_terms' => 'favicon,apple,touch,icon'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'SiteFaviconManifestLink',
                'config_value' => 'public/uploads/files/favicon/site.webmanifest',
                'group' => 'meta_seo',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Web manifest file link for the frontend interface.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-file-list-3-line',
                'search_terms' => 'favicon,manifest,site,web'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FrontEndFormat',
                'config_value' => 'MVC',
                'group' => 'api',
                'data_type' => 'Select',
                'options' => 'MVC,API',
                'default_value' => 'MVC',
                'deletable' => 0,
                'description' => 'Set frontend format to use MVC or API structure.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => 'Set to use MVC or API for frontend.',
                'icon' => 'ri-layout-2-line',
                'search_terms' => 'frontend,format,mvc,api'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'AllowedApiGetModels',
                'config_value' => 'BlogsModel, CategoriesModel, CodesModel, ConfigurationsModel, ContactsModel, ContactMessagesModel, ContentBlocksModel, CountersModel, CountriesModel, EventsModel, FaqsModel, FileUploadsModel, HomePageModel, LanguagesModel, NavigationsModel, PagesModel, PartnersModel, PortfoliosModel, PricingsModel, ServicesModel, SocialsModel, TeamsModel, TestimonialsModel, ThemesModel, TranslationsModel, UsersModel',
                'group' => 'api',
                'data_type' => 'Textarea',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'List of models allowed for API GET requests.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-database-2-line',
                'search_terms' => 'api,get,models,allowed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseCaptcha',
                'config_value' => 'No',
                'group' => 'forms',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable CAPTCHA for forms.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'captcha,security,forms,spam'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HCaptchaSiteKey',
                'config_value' => '',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'hCaptcha is a platform that stops online fraud and abuse with no personal information. It offers high accuracy, low friction, and universal compatibility for web, mobile, and server-side use cases. Learn more: https://www.hcaptcha.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-key-2-line',
                'search_terms' => 'recaptcha,key,site,hcaptcha'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HCaptchaSecretKey',
                'config_value' => configDataEncryption('ES_XXXXXXXXXX'),
                'group' => 'security',
                'data_type' => 'Secret',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'hCaptcha is a platform that stops online fraud and abuse with no personal information. It offers high accuracy, low friction, and universal compatibility for web, mobile, and server-side use cases. Learn more: https://www.hcaptcha.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-key-line',
                'search_terms' => 'recaptcha,secret,key,hcaptcha'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseShareThis',
                'config_value' => 'Yes',
                'group' => 'share',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'ShareThis official site. Digital data solutions for media planning, targeting, and measurement. Website tools to grow online audiences. Learn more: https://sharethis.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-share-line',
                'search_terms' => 'share,social,buttons,sharing'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ShareThisCode',
                'config_value' => '<script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=6XXXXXXXXXXXXXXXXXX&product=sticky-share-buttons&source=platform" async="async"></script>',
                'group' => 'share',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'You can install the ShareThis share button on your HTML website in a few easy steps. Navigate to the setup page and choose your preference of Inline Buttons or Sticky Buttons. Learn more: https://sharethis.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-share-line',
                'search_terms' => 'share,code,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseGoogleAnalytics',
                'config_value' => 'Yes',
                'group' => 'analytics',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable Google Analytics tracking.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-bar-chart-line',
                'search_terms' => 'analytics,google,tracking'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'GoogleAnalyticsCode',
                'config_value' => "<!--Google Tag Manager--><script async src='https://www.googletagmanager.com/gtag/js?id=YOUR_MEASUREMENT_ID'></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'YOUR_MEASUREMENT_ID');</script><!--End Google Tag Manager-->",
                'group' => 'analytics',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Embed code for Google Analytics tracking.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-google-line',
                'search_terms' => 'analytics,google,tag manager'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UsePostHog',
                'config_value' => 'No',
                'group' => 'forms',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable PostHog analytics script.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'analytics,posthog,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'PostHogCode',
                'config_value' => '<script>!function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(t,o,n){    function i(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){    t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}var s=e;for(void 0!==n?s=e[n]=[]:n="posthog",    s.people=s.people||[],s.toString=function(t){var e="posthog";return"posthog"!==n&&(e+="."+n),t||(e+=" (stub)"),e},    s.people.toString=function(){return s.toString(1)+".people (stub)"};p="capture identify alias people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" "),    r=0;r<p.length;r++)i(s,p[r]);e._i.push([t,o,n])},e.__SV=1.0,o=t.createElement("script"),    o.type="text/javascript",o.async=!0,o.src="https://cdn.posthog.com/posthog.js",n=t.getElementsByTagName("script")[0],    n.parentNode.insertBefore(o,n))}(document,window.posthog||[]);    posthog.init("YOUR_PROJECT_API_KEY", {api_host: "https://app.posthog.com"});</script>',
                'group' => 'share',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Add this snippet to your website within the <head> tag and you\'ll be ready to start using PostHog. Learn more: https://posthog.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'analytics,posthog,script'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableInstallationTracking',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable installation tracking. Only executed once if yes.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'tracking,installation,stat'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'InstallationTracked',
                'config_value' => 'No',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Checks if installation is tracked.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-line-chart-fill',
                'search_terms' => 'tracking,installation,stat'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseCookieConcent',
                'config_value' => 'Yes',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable cookie consent banner.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'security,cookie,consent'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'CookieConcentCode',
                'config_value' => '<!-- Cookie Consent by TermsFeed https://www.TermsFeed.com --><script type="text/javascript" src="https://www.termsfeed.com/public/cookie-consent/4.2.0/cookie-consent.js" charset="UTF-8"></script><script type="text/javascript" charset="UTF-8">document.addEventListener("DOMContentLoaded", function () {cookieconsent.run({"notice_banner_type":"simple","consent_type":"express","palette":"light","language":"en","page_load_consent_levels":["strictly-necessary"],"notice_banner_reject_button_hide":false,"preferences_center_close_button_hide":false,"page_refresh_confirmation_buttons":false,"website_name":"Igniter CMS"});});</script><noscript>Free cookie consent management tool by <a href="https://www.termsfeed.com/">TermsFeed Generator</a></noscript><!-- End Cookie Consent by TermsFeed https://www.TermsFeed.com --><a href="#" id="open_preferences_center">Update cookies preferences</a>',
                'group' => 'security',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Cookie Consent solution for your website to comply with ePrivacy Directive & GDPR. See options: https://termly.io/, https://www.freeprivacypolicy.com/free-cookie-consent/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shield-check-line',
                'search_terms' => 'security,cookie,consent'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'UseTwitterFeed',
                'config_value' => 'Yes',
                'group' => 'analytics',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable Twitter feed integration.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-twitter-line',
                'search_terms' => 'analytics,twitter,feed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'TwitterFeedCode',
                'config_value' => '<blockquote class="twitter-tweet" data-dnt="true" align="center"><p lang="en" dir="ltr">It&#39;s pretty awesome how dancing makes robots less intimidating. Looking forward to seeing more nontrivial Machine Learning on these robots. Credit: Boston Dynamics. <a href="https://t.co/wnB2i9qhdQ">pic.twitter.com/wnB2i9qhdQ</a></p>&mdash; Reza Zadeh (@Reza_Zadeh) <a href="https://twitter.com/Reza_Zadeh/status/1344009123004747778?ref_src=twsrc%5Etfw">December 29, 2020</a></blockquote><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>',
                'group' => 'security',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Embed X/Twitter feeds in your web page. See options : https://publish.twitter.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-twitter-line',
                'search_terms' => 'analytics,twitter,feed'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableGeminiAI',
                'config_value' => 'Yes',
                'group' => 'ai',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable Gemini AI integration.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'ai,chat,help,gemini,deepseek,qwen,gpt,enable'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableGeminiAIAnalysis',
                'config_value' => 'Yes',
                'group' => 'ai',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable Gemini AI for analysis of site data. This may include sharing of sensitive data with the AI',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'ai,chat,help,gemini,deepseek,qwen,gpt,enable'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'GeminiAPIKey',
                'config_value' => '',
                'group' => 'ai',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => '',
                'deletable' => 0,
                'description' => 'API key for the AI service to use (e.g., Gemini).',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-fill',
                'search_terms' => 'ai,chat,help,gemini,deepseek,qwen,gpt'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'GeminiBaseURL',
                'config_value' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=',
                'group' => 'ai',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=',
                'deletable' => 0,
                'description' => 'Base URL for the API AI service to use (e.g., Gemini).',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-fill',
                'search_terms' => 'ai,base url,chat,help,gemini,deepseek,qwen,gpt'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableChatbot',
                'config_value' => 'Yes',
                'group' => 'chatbot',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable chatbot integration.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'chatbot,enable'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'ChatbotCode',
                'config_value' => '<!--Start of Tawk.to Script--><script type="text/javascript">var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();(function(){var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];s1.async=true;s1.src="https://embed.tawk.to/[tawk.to.code]";s1.charset="UTF-8";s1.setAttribute("crossorigin","*");s0.parentNode.insertBefore(s1,s0);})();</script><!--End of Tawk.to Script-->',
                'group' => 'chatbot',
                'data_type' => 'Code',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Integrate chatbots and monitor customer activity in real time. See options like: https://www.tawk.to/, https://zapier.com/, https://botpress.com/, https://webagent.ai/, https://botpenguin.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-robot-2-line',
                'search_terms' => 'chatbot,tawk.to'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableGoogleTranslate',
                'config_value' => 'No',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'No',
                'deletable' => 0,
                'description' => 'Enable or disable Google Translate feature.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-earth-line',
                'search_terms' => 'translate,google,language'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableGlobalSearchIcon',
                'config_value' => 'Yes',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Enable or disable global search icon feature.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-search-line',
                'search_terms' => 'search,global search,search modal'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'HoneypotKey',
                'config_value' => 'igniter_hpot_val',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => 'igniter_hpot_val',
                'deletable' => 0,
                'description' => 'This is the input name for your honeypot input.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shield-keyhole-fill',
                'search_terms' => 'honeypot,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'TimestampKey',
                'config_value' => 'igniter_timestamp_val',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => 'igniter_timestamp_val',
                'deletable' => 0,
                'description' => 'This is the input name for your timestamp bot detector.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-shield-keyhole-fill',
                'search_terms' => 'honeypot,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaxFailedAttempts',
                'config_value' => '5',
                'group' => 'security',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => '5',
                'deletable' => 0,
                'description' => 'This is maximum failed login attempts allowed in one session.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-lock-fill',
                'search_terms' => 'failed login,locked out,security'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'FailedLoginsSuspensionPeriod',
                'config_value' => '+30 minutes',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => '+5 minutes,+10 minutes,+30 minutes,+1 hour,+3 hours,+24 hours',
                'default_value' => '+30 minutes',
                'deletable' => 0,
                'description' => 'This is suspension period for multiple failed logins.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-time-fill',
                'search_terms' => 'suspension,failed login,locked out,security, timeout'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'BlockedIPSuspensionPeriod',
                'config_value' => '+3 years',
                'group' => 'security',
                'data_type' => 'Select',
                'options' => '+1 day,+1 days,+1 month,+3 months,+6 months,+1 year,+3 years,+5 years,+10 years',
                'default_value' => '+3 years',
                'deletable' => 0,
                'description' => 'This is suspension period for suspended IP\'s.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-time-fill',
                'search_terms' => 'suspension,bot detection,spam,security, block ip'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'MaxUploadFileSize',
                'config_value' => '1',
                'group' => 'site',
                'data_type' => 'Select',
                'options' => '1,3,5,10,50,100,1000',
                'default_value' => '5',
                'deletable' => 0,
                'description' => 'This is the maximum file upload size in megabytes.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-upload-cloud-fill',
                'search_terms' => 'file upload,maximum,file size'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableDisqusComments',
                'config_value' => 'Yes',
                'group' => 'comment',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Disqus offers the best add-on tools for websites to increase engagement. Learn more: https://www.disqus.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-disqus-line',
                'search_terms' => 'disqus,comments,discussion,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableDisqusCommentCount',
                'config_value' => 'Yes',
                'group' => 'comment',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Disqus offers the best add-on tools for websites to increase engagement. Learn more: https://www.disqus.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-disqus-line',
                'search_terms' => 'disqus,comments,discussion,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'DisqusShortName',
                'config_value' => 'https://your-disqus-shortname.disqus.com/',
                'group' => 'comment',
                'data_type' => 'Text',
                'options' => null,
                'default_value' => null,
                'deletable' => 0,
                'description' => 'Provide your disqus shortname link here (e.g. https://your-disqus-shortname.disqus.com/). Do not include "/embed.js" or "/count.js". Learn more: https://www.disqus.com/',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-disqus-line',
                'search_terms' => 'disqus,comments,discussion,settings'
            ],
            [
                'config_id' => getGUID(),
                'config_for' => 'EnableIgniterNewsFeed',
                'config_value' => 'Yes',
                'group' => 'comment',
                'data_type' => 'Select',
                'options' => 'Yes,No',
                'default_value' => 'Yes',
                'deletable' => 0,
                'description' => 'Get latest news, features, and security update feeds from Igniter CMS.',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'custom_class' => '',
                'icon' => 'ri-newspaper-line',
                'search_terms' => 'igniter-cms,news feed,security updates'
            ],
        ];

        // Using Query Builder
        $this->db->table('configurations')->insertBatch($data);
    }

    public function down()
    {
        $this->forge->dropTable('configurations');
    }
}