<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class AnnouncementPopups extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'popup_id' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
            ],
            'name' => [
                'type' => 'VARCHAR',
                'constraint' => 255
            ],
            'type' => [
                'type' => 'INT',
                'constraint' => 1,
            ],
            'title' => [
                'type' => 'TEXT',
            ],
            'text' => [
                'type' => 'TEXT',
                'null' => true
            ],
            'button_text' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'button_color' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'cancel_button_text' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'cancel_button_color' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'link' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'new_tab' => [
                'type' => 'BOOLEAN',
                'default' => false,
                'null' => true,
            ],
            'delay' => [
                'type' => 'INT',
                'null' => true,
                'default' => 1000,
            ],
            'image' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'preview_image' => [
                'type' => 'VARCHAR',
                'constraint' => '255',
                'null' => true,
            ],
            'background_color' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'text_color' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true
            ],
            'backdrop_opacity' => [
                'type' => 'FLOAT',
                'null' => true,
                'default' => 0.7,
            ],
            'width' => [
                'type' => 'INT',
                'null' => true,
            ],
            'height' => [
                'type' => 'INT',
                'null' => true,
            ],
            'position' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'animation' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'show_close_button' => [
                'type' => 'BOOLEAN',
                'default' => true,
                'null' => true,
            ],
            'enable_subscription' => [
                'type' => 'BOOLEAN',
                'default' => false,
                'null' => true,
            ],
            'subscription_placeholder' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'subscription_success_message' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'enable_countdown' => [
                'type' => 'BOOLEAN',
                'default' => false,
                'null' => true,
            ],
            'countdown_end_date' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'countdown_format' => [
                'type' => 'VARCHAR',
                'constraint' => 50,
                'null' => true,
            ],
            'countdown_expired_text' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'order' => [
                'type' => 'INT',
                'null' => true,
                'default' => 10,
            ],
            'status' => [
                'type' => 'INT',
                'default' => 0,
                'null' => true,
            ],
            'frequency' => [
                'type' => 'FLOAT',
                'null' => true,
            ],
            'start_date' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'end_date' => [
                'type' => 'DATETIME',
                'null' => true,
            ],
            'show_on_pages' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'deletable' => [
                'type' => 'INT',
                'default' => 1,
            ],
            'created_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'updated_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);
        $this->forge->addKey('popup_id', true);

        // Custom Optimization - Indexing
        $this->forge->addKey('name');
        $this->forge->addKey('title');
        $this->forge->addKey('text');

        $this->forge->createTable('announcement_popups');

        //insert default records
        //----------------------
        $data = [
            [
                'popup_id' => getGUID(),
                'name' => 'TypeOneAdvert',
                'type' => 1, 
                'title' => 'Special Offer!',
                'text' => 'Discover our amazing products with exclusive discounts!',
                'button_text' => 'Shop Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Maybe Later',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=we-are-open'),
                'new_tab' => true,
                'delay' => 2000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-1.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-1-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => '',
                'subscription_success_message' => '',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 1,
                'status' => 1,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeTwoAdvert',
                'type' => 2,
                'title' => 'Special Offer!',
                'text' => 'Get 30% off on all premium subscriptions',
                'button_text' => 'Get Offer Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Close',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=big-sale'),
                'new_tab' => true,
                'delay' => 3000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-2.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-2-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => '',
                'subscription_success_message' => '',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 2,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeThreeAdvert',
                'type' => 3,
                'title' => 'Subscribe to Our Newsletter',
                'text' => 'Stay updated with our latest offers!',
                'button_text' => 'Subscribe Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Close',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=we-are-open'),
                'new_tab' => true,
                'delay' => 2000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-3.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-3-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => 'Enter your email',
                'subscription_success_message' => 'Thank you for subscribing!',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 3,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeFourAdvert',
                'type' => 4,
                'title' => 'Amazing Offer!',
                'text' => 'Don\'t miss out on our exclusive offer. Shop now and save big on your favorite items!',
                'button_text' => 'Leanr more',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Close',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=big-sale'),
                'new_tab' => true,
                'delay' => 3000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-4.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-4-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => '',
                'subscription_success_message' => '',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 4,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeFiveAdvert',
                'type' => 5,
                'title' => 'Join Our Community',
                'text' => 'Subscribe to get exclusive updates and offers!',
                'button_text' => 'Subscribe',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'No, thanks',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=subscribe-now'),
                'new_tab' => true,
                'delay' => 4000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-5.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-5-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 1000,
                'height' => 800,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => true,
                'subscription_placeholder' => 'Enter your email address',
                'subscription_success_message' => 'Thank you for subscribing!',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 5,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeSixAdvert',
                'type' => 6,
                'title' => 'Limited Time Offer!',
                'text' => 'Don\'t miss out on this exclusive deal.',
                'button_text' => 'Claim Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Later',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=new-collection'),
                'new_tab' => true,
                'delay' => 5000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-6.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-6-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => '',
                'subscription_success_message' => '',
                'enable_countdown' => true,
                'countdown_end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 3 days')),
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 6,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeSevenAdvert',
                'type' => 7,
                'title' => 'Flash Sale!',
                'text' => 'Huge discounts on premium packages',
                'button_text' => 'Shop Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Later',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=limited-time-offer'),
                'new_tab' => true,
                'delay' => 6000,
                'image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-7.jpg',
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-7-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => false,
                'subscription_placeholder' => '',
                'subscription_success_message' => '',
                'enable_countdown' => true,
                'countdown_end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 3 days')),
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 7,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
            [
                'popup_id' => getGUID(),
                'name' => 'TypeEightAdvert',
                'type' => 8,
                'title' => 'Subscribe to Our Newsletter',
                'text' => 'Stay updated with our latest offers!',
                'button_text' => 'Subscribe Now',
                'button_color' => '#0484B2',
                'cancel_button_text' => 'Later',
                'cancel_button_color' => '#d33',
                'link' => base_url('/?popup=new-collection'),
                'new_tab' => true,
                'delay' => 5000,
                'image' => null,
                'preview_image' => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/adverts/type-8-preview.png',
                'background_color' => '#ffffff',
                'text_color' => '#000000',
                'backdrop_opacity' => 0.7,
                'width' => 900,
                'height' => 600,
                'position' => 'center',
                'animation' => 'animate__fadeIn',
                'show_close_button' => true,
                'enable_subscription' => true,
                'subscription_placeholder' => 'Enter your email',
                'subscription_success_message' => 'Thank you for subscribing!',
                'enable_countdown' => false,
                'countdown_end_date' => null,
                'countdown_format' => 'DD:HH:MM:SS',
                'countdown_expired_text' => '',
                'order' => 8,
                'status' => 0,
                'frequency' => 1,
                'start_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s'))),
                'end_date' => date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s') . ' + 7 days')),
                'show_on_pages' => 'home,pages,shop',
                'created_by' => getGUID(getDefaultAdminGUID()),
                'updated_by' => null,
                'deletable'    => 0
            ],
        ];

        // Using Query Builder
        $this->db->table('announcement_popups')->insertBatch($data);
    }

    public function down()
    {
        $this->forge->dropTable('announcement_popups');
    }
}
