<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class HomePage extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'home_page_id' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
            ],
            'section' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
            ],
            'section_title' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
            ],
            'section_description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'section_image' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_image_2' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_image_3' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_image_4' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_video' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_audio' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'section_file' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'content_blocks' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'section_link' => [
                'type' => 'VARCHAR',
                'constraint' => 255,
                'null' => true,
            ],
            'new_tab' => [
                'type' => 'BOOLEAN',
                'default' => false,
                'null' => true,
            ],
            'status' => [
                'type' => 'INT',
                'default' => 0,
                'null' => true,
            ],
            'order' => [
                'type' => 'INT',
                'null' => true,
                'default' => 10,
            ],
            'deletable' => [
                'type' => 'INT',
                'default' => 1,
            ],
            'created_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'updated_by' => [
                'type' => 'VARCHAR',
                'constraint' => '50',
                'null' => true,
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);
        $this->forge->addKey('home_page_id', true);

        // Custom Optimization - Indexing
        $this->forge->addKey('section');
        $this->forge->addKey('section_title');
        $this->forge->addKey('section_description');

        $this->forge->createTable('home_page');

        //Insert default record
        $data = [
            [
                'home_page_id' => getGUID(),
                'section'    => 'HomeHero',
                'section_title'    => 'A Bootstrap 5 template for modern businesses',
                'section_description'    => 'Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit!',
                'section_image'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/hero-img.svg',
                'section_image_2'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/hero-carousel-1.jpg',
                'section_image_3'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/hero-carousel-2.jpg',
                'section_image_4'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/hero-carousel-3.jpg',
                'section_video'    => 'https://www.youtube.com/watch?v=sQ22pm-xvrE',
                'section_audio'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/sample-audio-1.mp3',
                'section_file'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/sample.pdf',
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 2,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'HomeAbout',
                'section_title'    => 'About Us',
                'section_description'    => 'Welcome to A Bootstrap 5 Template for Modern Businesses! Our mission is to provide sleek, responsive, and highly customizable templates that empower businesses to create stunning websites with ease. Whether you\'re a startup, a growing company, or an established enterprise, our templates are designed to meet your needs and help you stand out in the digital landscape.',
                'section_image'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/home-about.jpg',
                'section_image_2'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/why-us.png',
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => 'https://www.youtube.com/watch?v=sQ22pm-xvrE',
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 4,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Services',
                'section_title'    => 'Services',
                'section_description'    => 'Discover our range of professional services designed to help your business thrive. From web development and design to digital marketing and consulting, we offer tailored solutions to meet your unique needs and drive your success.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 6,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Counters',
                'section_title'    => 'Counters',
                'section_description'    => '',
                'section_image'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/skills.png',
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 8,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Pricing',
                'section_title'    => 'Pricing',
                'section_description'    => 'Get transparent and competitive pricing for all our services. We offer flexible packages to suit different budgets and requirements, ensuring you get the best value for your investment.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 12,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'FrequentlyAskedQuestions',
                'section_title'    => 'Frequently Asked Questions',
                'section_description'    => 'Have questions? We\'ve got answers. Check out our FAQ section for quick and helpful responses to the most common inquiries about our services, processes, and more.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 14,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Testimonials',
                'section_title'    => 'Testimonials',
                'section_description'    => '',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 16,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Portfolio',
                'section_title'    => 'Portfolio',
                'section_description'    => 'Explore our portfolio to see the innovative projects we\'ve completed for our clients. Our work showcases our commitment to quality, creativity, and excellence across various industries and project types.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 18,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Team',
                'section_title'    => 'Team',
                'section_description'    => 'Meet the talented individuals behind our success. Our team of experts brings diverse skills and experiences to the table, working collaboratively to deliver outstanding results for our clients.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 20,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Partners',
                'section_title'    => 'Partners',
                'section_description'    => 'We are proud to be supported by our amazing sponsors. Their contributions help us deliver top-notch services and continue to innovate. Thank you for your support!',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 22,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'CallToAction',
                'section_title'    => 'Call To Action',
                'section_description'    => 'Ready to take your business to the next level? Contact us today to get started on your journey to success. Let\'s build something amazing together!',
                'section_image'    => 'public/uploads/file-uploads/admin_8J0IM/01-12-2024/hero-carousel-1.jpg',
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => 'https://www.youtube.com/watch?v=sQ22pm-xvrE',
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => '#!',
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 24,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'RecentPosts',
                'section_title'    => 'Recent Posts',
                'section_description'    => 'Stay updated with the latest trends, tips, and insights in the industry through our blog. Our expert articles cover a wide range of topics to help you stay informed and ahead of the curve.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 26,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Subscribe',
                'section_title'    => 'New products, delivered to you.',
                'section_description'    => 'Sign up for our newsletter for the latest updates.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 28,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ],
            [
                'home_page_id' => getGUID(),
                'section'    => 'Contact',
                'section_title'    => 'Get in touch',
                'section_description'    => 'We\'d love to hear from you! Reach out to us through our contact page for any inquiries, feedback, or to discuss how we can help your business grow. We\'re here to assist you every step of the way.',
                'section_image'    => null,
                'section_image_2'    => null,
                'section_image_3'    => null,
                'section_image_4'    => null,
                'section_video'    => null,
                'section_audio'    => null,
                'section_file'    => null,
                'content_blocks'    => null,
                'section_link'    => null,
                'new_tab'    => false,
                'status'    => '1',
                'order'    => 30,
                'created_by'    => getGUID(getDefaultAdminGUID()),
                'updated_by'    => null,
                'deletable'    => 0
            ]
        ];

        // Using Query Builder
        $this->db->table('home_page')->insertBatch($data);
    }
    
    public function down()
    {
        $this->forge->dropTable('home_page');
    }
}
